import argparse
import csv
import os
import pickle

import _init_paths


def _auc_per_sequence(eval_data):
    success = eval_data["ave_success_rate_plot_overlap"]
    return [[sum(curve) / len(curve) * 100.0 for curve in seq_curves] for seq_curves in success]


def _precision_at(eval_data, key, threshold):
    values = eval_data[key]
    if key == "ave_success_rate_plot_center":
        thresholds = eval_data["threshold_set_center"]
    else:
        thresholds = eval_data["threshold_set_center_norm"]
    index = min(range(len(thresholds)), key=lambda idx: abs(thresholds[idx] - threshold))
    return [[seq_values[tracker_idx][index] * 100.0 for tracker_idx in range(len(seq_values))]
            for seq_values in values]


def main():
    parser = argparse.ArgumentParser(description="Export TEC stage1 per-sequence attribution.")
    parser.add_argument(
        "--eval_data",
        type=str,
        default="output/test/result_plots/otb_lang_tec_stage1/eval_data.pkl",
        help="Path to eval_data.pkl generated by analysis_results_tec_stage1.py.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="output/diagnostics/tec_stage1_per_sequence.csv",
        help="CSV file to write.",
    )
    args = parser.parse_args()

    with open(args.eval_data, "rb") as f:
        eval_data = pickle.load(f)

    trackers = [tracker["disp_name"] for tracker in eval_data["trackers"]]
    expected = ["A0_baseline_ep47", "A1_TEC_normal_ep5", "A1_TEC_wrong_ep5", "A1_TEC_generic_ep5"]
    if trackers[:4] != expected:
        raise ValueError("Unexpected tracker order: {}".format(trackers))

    auc = _auc_per_sequence(eval_data)
    precision = _precision_at(eval_data, "ave_success_rate_plot_center", 20)
    norm_precision = _precision_at(eval_data, "ave_success_rate_plot_center_norm", 0.5)

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    rows = []
    for seq_name, auc_row, prec_row, norm_row in zip(
            eval_data["sequences"], auc, precision, norm_precision):
        a0, normal, wrong, generic = auc_row[:4]
        normal_minus_best_control = normal - max(wrong, generic)
        rows.append({
            "sequence": seq_name,
            "a0_auc": a0,
            "a1_normal_auc": normal,
            "a1_wrong_auc": wrong,
            "a1_generic_auc": generic,
            "normal_minus_a0": normal - a0,
            "wrong_minus_a0": wrong - a0,
            "generic_minus_a0": generic - a0,
            "normal_minus_wrong": normal - wrong,
            "normal_minus_generic": normal - generic,
            "normal_minus_best_control": normal_minus_best_control,
            "best_variant": ["A0", "normal", "wrong", "generic"][max(range(4), key=lambda idx: auc_row[idx])],
            "a0_precision20": prec_row[0],
            "normal_precision20": prec_row[1],
            "wrong_precision20": prec_row[2],
            "generic_precision20": prec_row[3],
            "a0_norm_precision": norm_row[0],
            "normal_norm_precision": norm_row[1],
            "wrong_norm_precision": norm_row[2],
            "generic_norm_precision": norm_row[3],
        })

    fieldnames = list(rows[0].keys())
    with open(args.output, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    improved = sum(row["normal_minus_a0"] > 0 for row in rows)
    language_positive = sum(row["normal_minus_best_control"] > 0 for row in rows)
    print("Wrote {}".format(args.output))
    print("normal > A0: {}/{}".format(improved, len(rows)))
    print("normal > max(wrong, generic): {}/{}".format(language_positive, len(rows)))


if __name__ == "__main__":
    main()
