from easydict import EasyDict as edict
import yaml

"""
Add default config for OSTrack.
"""
cfg = edict()

# MODEL
cfg.MODEL = edict()
cfg.MODEL.PRETRAIN_FILE = "mae_pretrain_vit_base.pth"
cfg.MODEL.EXTRA_MERGER = False

cfg.MODEL.RETURN_INTER = False
cfg.MODEL.RETURN_STAGES = []

# MODEL.BACKBONE
cfg.MODEL.BACKBONE = edict()
cfg.MODEL.BACKBONE.TYPE = "vit_base_patch16_224"
cfg.MODEL.BACKBONE.STRIDE = 16
cfg.MODEL.BACKBONE.MID_PE = False
cfg.MODEL.BACKBONE.SEP_SEG = False
cfg.MODEL.BACKBONE.CAT_MODE = 'direct'
cfg.MODEL.BACKBONE.MERGE_LAYER = 0
cfg.MODEL.BACKBONE.ADD_CLS_TOKEN = False
cfg.MODEL.BACKBONE.TOKEN_LEN = 1
cfg.MODEL.BACKBONE.TOP_K = 3
cfg.MODEL.BACKBONE.CLS_TOKEN_USE_MODE = 'ignore'
cfg.MODEL.BACKBONE.ATTN_TYPE = 'concat'

cfg.MODEL.BACKBONE.CE_LOC = []
cfg.MODEL.BACKBONE.CE_KEEP_RATIO = []
cfg.MODEL.BACKBONE.CE_TEMPLATE_RANGE = 'ALL'  # choose between ALL, CTR_POINT, CTR_REC, GT_BOX
cfg.MODEL.BACKBONE.BERT_DIR = 'ALL'
cfg.MODEL.BACKBONE.BLIP_DIR = 'ALL'

# MODEL.HEAD
cfg.MODEL.HEAD = edict()
cfg.MODEL.HEAD.TYPE = "CENTER"
cfg.MODEL.HEAD.NUM_CHANNELS = 256

# MODEL.TE
cfg.MODEL.TE = edict()
cfg.MODEL.TE.ENABLE = False
cfg.MODEL.TE.PRUNING_LOC = [3, 7, 11]
cfg.MODEL.TE.HARD = False
cfg.MODEL.TE.TAU = 1.0
cfg.MODEL.TE.KEEP_VL = False
cfg.MODEL.TE.KEEP_LV = False
cfg.MODEL.TE.BIDIR_MODE = "sequential"  # sequential, parallel
cfg.MODEL.TE.KEEP_VL_SOURCE = "global"  # global, template_match, safe_multi_proto, word_safe_multi_proto, word_direct
cfg.MODEL.TE.HIDDEN_DIM = 256
cfg.MODEL.TE.LANG_RESIDUAL_BETA = 0.1
cfg.MODEL.TE.PROTO_TOPK_TARGET = 4
cfg.MODEL.TE.PROTO_TOPK_NEGATIVE = 8
cfg.MODEL.TE.PROTO_CONTRAST_TAU = 0.2
cfg.MODEL.TE.SAFE_CONFIRM_GAMMA = 0.35
cfg.MODEL.TE.SAFE_CONFIRM_TAU = 0.0
cfg.MODEL.TE.SAFE_CONFIRM_MAX = 0.25
cfg.MODEL.TE.NEGATIVE_GATE_SCALE = 8.0
cfg.MODEL.TE.NEGATIVE_GATE_FLOOR = 0.05
cfg.MODEL.TE.WORD_WEIGHT_TAU = 0.07
cfg.MODEL.TE.WORD_TEMPLATE_WEIGHT = 1.0
cfg.MODEL.TE.WORD_SEARCH_WEIGHT = 0.5
cfg.MODEL.TE.WORD_LEARNED_WEIGHT = 0.1
cfg.MODEL.TE.LMQ_ENABLE = False
cfg.MODEL.TE.LMQ_LOC = [15]
cfg.MODEL.TE.LMQ_NUM_QUERIES = 4
cfg.MODEL.TE.LMQ_HIDDEN_DIM = 256
cfg.MODEL.TE.LMQ_DROPOUT = 0.0
cfg.MODEL.TE.LMQ_SEED_RESIDUAL = False
cfg.MODEL.TE.LMQ_SEED_RESIDUAL_GAMMA = 0.1
cfg.MODEL.TE.LMQ_DECODER_ENABLE = False
cfg.MODEL.TE.LMQ_DECODER_NUM_HEADS = 8
cfg.MODEL.TE.LMQ_DECODER_DROPOUT = 0.1
cfg.MODEL.TE.LMQ_DECODER_FFN_RATIO = 2.0
cfg.MODEL.TE.LANGUAGE_STATE_ENABLE = False
cfg.MODEL.TE.LANGUAGE_STATE_HIDDEN_DIM = 256
cfg.MODEL.TE.LANGUAGE_STATE_MAX_DELTA = 0.1
cfg.MODEL.TE.LANGUAGE_STATE_DROPOUT = 0.0
cfg.MODEL.TE.LANGUAGE_STATE_INIT_GATE_BIAS = -4.0
cfg.MODEL.TE.LANGUAGE_STATE_SOURCE_INIT_GATE_BIAS = None
cfg.MODEL.TE.LANGUAGE_STATE_INIT_DELTA_STD = 0.0001
cfg.MODEL.TE.LANGUAGE_STATE_RELATION_LAYERS = 1
cfg.MODEL.TE.LANGUAGE_STATE_RELATION_HEADS = 4
cfg.MODEL.TE.LANGUAGE_STATE_ALIGNMENT = "position"  # position, cross_attn
cfg.MODEL.TE.LANGUAGE_STATE_ALIGNMENT_HEADS = 4
cfg.MODEL.TE.LANGUAGE_STATE_VISUAL_EVIDENCE_DIM = 8
cfg.MODEL.TE.LANGUAGE_STATE_UPDATE_MODE = "residual"  # residual, keep_absorb, decoupled
cfg.MODEL.TE.GLOBAL_SCORE_BIAS_ENABLE = False
cfg.MODEL.TE.GLOBAL_SCORE_BIAS_HIDDEN_DIM = 256
cfg.MODEL.TE.GLOBAL_SCORE_BIAS_MAX_DELTA = 0.02
cfg.MODEL.TE.GLOBAL_SCORE_BIAS_INIT_GATE_BIAS = -4.0
cfg.MODEL.TE.GLOBAL_SCORE_BIAS_INIT_DELTA_STD = 0.0001
cfg.MODEL.TE.GLOBAL_SCORE_BIAS_POOL_MODE = "mean"  # mean, cls, attention
cfg.MODEL.TE.GLOBAL_SCORE_BIAS_BETA = 0.02
cfg.MODEL.TE.POLICY_APPLY = "post_softmax"  # post_softmax, pre_softmax, none
cfg.MODEL.TE.QUERY_SCOPE = "all"  # all, q0, track, track_search, search, visual, track_visual
cfg.MODEL.TE.PRE_SOFTMAX_LAMBDA = 1.0
cfg.MODEL.TE.PRE_SOFTMAX_CENTER = "none"  # none, visual, separate
cfg.MODEL.TE.POLICY_EPS = 0.0001
cfg.MODEL.TE.SCORE_PRIOR_ENABLE = False
cfg.MODEL.TE.SCORE_PRIOR_BETA = 0.0
cfg.MODEL.TE.SCORE_PRIOR_SOURCE = "logits"  # logits, decision, word_direct_margin, lmq_prior
cfg.MODEL.TE.SCORE_PRIOR_CENTER = "mean"  # mean, none
cfg.MODEL.TE.SCORE_PRIOR_LAYER = -1  # -1 means the last TE stage; otherwise match a value in PRUNING_LOC
cfg.MODEL.TE.SCORE_PRIOR_EPS = 0.0001
cfg.MODEL.TE.SCORE_PRIOR_BIAS_CLAMP = 0.0
cfg.MODEL.TE.SCORE_PRIOR_MARGIN_TAU = 0.1
cfg.MODEL.TE.AUX_SEARCH_LOSS_WEIGHT = 0.0
cfg.MODEL.TE.AUX_SEARCH_LOSS = "bce"  # bce, rank, center_rank
cfg.MODEL.TE.AUX_SEARCH_TARGET = "box"  # box, soft_center
cfg.MODEL.TE.AUX_CENTER_SIGMA_SCALE = 0.35
cfg.MODEL.TE.AUX_CENTER_MIN_SIGMA = 0.04
cfg.MODEL.TE.AUX_CENTER_BASE_QUALITY = 0.3
cfg.MODEL.TE.AUX_CENTER_NEG_QUALITY = 0.2
cfg.MODEL.TE.AUX_RANK_MARGIN = 0.2
cfg.MODEL.TE.AUX_HARD_NEG_RATIO = 0.1
cfg.MODEL.TE.AUX_AREA_WEIGHT = 0.05
cfg.MODEL.TE.AUX_AREA_MULTIPLIER = 1.5
cfg.MODEL.TE.AUX_AREA_MIN = 0.02
cfg.MODEL.TE.AUX_AREA_MAX = 0.5
cfg.MODEL.TE.AUX_SEARCH_LOSS_ANNEAL = "none"  # none, linear, cosine
cfg.MODEL.TE.AUX_SEARCH_LOSS_WEIGHT_END = 0.0
cfg.MODEL.TE.AUX_SEARCH_ANNEAL_EPOCHS = 0
cfg.MODEL.TE.AUX_SCORE_LOSS_WEIGHT = 0.0
cfg.MODEL.TE.AUX_SCORE_LOSS_ANNEAL = "none"  # none, linear, cosine
cfg.MODEL.TE.AUX_SCORE_LOSS_WEIGHT_END = 0.0
cfg.MODEL.TE.AUX_SCORE_ANNEAL_EPOCHS = 0
cfg.MODEL.TE.AUX_SCORE_POS_QUALITY = 0.7
cfg.MODEL.TE.AUX_SCORE_POS_MAX_TOKENS = 4
cfg.MODEL.TE.AUX_SCORE_POS_MIN_QUALITY = 0.0
cfg.MODEL.TE.AUX_SCORE_HARD_NEG_RATIO = 0.02
cfg.MODEL.TE.AUX_SCORE_HARD_NEG_TOPK = 8
cfg.MODEL.TE.AUX_SCORE_HARD_NEG_MAX_QUALITY = 0.0
cfg.MODEL.TE.AUX_SCORE_CORRECTIVE_MARGIN = 0.05
cfg.MODEL.TE.AUX_SCORE_GAIN_MARGIN = 0.01
cfg.MODEL.TE.AUX_SCORE_GAIN_WEIGHT = 0.1
cfg.MODEL.TE.AUX_SCORE_BIAS_L2_WEIGHT = 0.001


# TRAIN
cfg.TRAIN = edict()
cfg.TRAIN.LR = 0.0001
cfg.TRAIN.WEIGHT_DECAY = 0.0001
cfg.TRAIN.EPOCH = 500
cfg.TRAIN.LR_DROP_EPOCH = 400
cfg.TRAIN.BATCH_SIZE = 16
cfg.TRAIN.GRAD_ACCUM_STEPS = 1
cfg.TRAIN.NUM_WORKER = 8
cfg.TRAIN.OPTIMIZER = "ADAMW"
cfg.TRAIN.BACKBONE_MULTIPLIER = 0.1
cfg.TRAIN.GIOU_WEIGHT = 2.0
cfg.TRAIN.L1_WEIGHT = 5.0
cfg.TRAIN.FREEZE_LAYERS = [0, ]
cfg.TRAIN.PRINT_INTERVAL = 50
cfg.TRAIN.VAL_EPOCH_INTERVAL = 20
cfg.TRAIN.GRAD_CLIP_NORM = 0.1
cfg.TRAIN.AMP = False
cfg.TRAIN.BBOX_TASK = False
cfg.TRAIN.TRAIN_TE_ONLY = False
cfg.TRAIN.TRAIN_TE_ONLY_PATTERNS = ["backbone.visual_te_predictors"]
cfg.TRAIN.LANGUAGE_STATE_TRAIN_ENABLE = False
cfg.TRAIN.LANGUAGE_STATE_DETACH_TEXT = True
cfg.TRAIN.LANGUAGE_STATE_VISUAL_EVIDENCE = "gt_motion"
cfg.TRAIN.LANGUAGE_STATE_GATE_LOSS_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_STATE_DELTA_LOSS_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_STATE_GAIN_LOSS_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_STATE_GAIN_MARGIN = 0.01
cfg.TRAIN.LANGUAGE_STATE_GAIN_HARDNEG_TOPK = 6
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_LOSS_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_MARGIN = 0.005
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_MARGIN_REL = 0.02
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_MARGIN_ABS = 0.005
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_HARDNEG_MARGIN = 0.0
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_IDENTITY_ENABLE = False
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_IDENTITY_MIN = 0.2
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_TOP_RATIO = 0.0
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_MAX_POS = 0
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_MULTI_FRAME = False
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_HARD_NEG_WEIGHT = 1.0
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_POS_FLOOR_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_POS_FLOOR_MIN = 0.3
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_SOFT_TARGET = False
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_SOFT_TAU = 0.02
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_FOCAL_GAMMA = 0.0
cfg.TRAIN.LANGUAGE_STATE_TOKEN_ABSORB_FOCAL_ALPHA = 0.75
cfg.TRAIN.LANGUAGE_STATE_ALIGN_CONTRAST_LOSS_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_STATE_ALIGN_CONTRAST_TAU = 0.07
cfg.TRAIN.LANGUAGE_STATE_CANDIDATE_CAP_LOSS_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_STATE_CANDIDATE_WEIGHT_MAX = 0.5
cfg.TRAIN.LANGUAGE_STATE_ANCHOR_CAP_LOSS_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_STATE_ANCHOR_WEIGHT_MAX = 0.5
cfg.TRAIN.LANGUAGE_STATE_PREV_KEEP_LOSS_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_STATE_PREV_KEEP_MIN = 0.5
cfg.TRAIN.STAGED_TRAINING = False
cfg.TRAIN.STAGE_SWITCH_EPOCH = 0
cfg.TRAIN.STAGE1_PATTERNS = ["backbone.visual_te_predictors"]
cfg.TRAIN.STAGE2_PATTERNS = [
    "backbone.visual_te_predictors",
    "box_head.conv1_ctr",
    "box_head.conv2_ctr",
    "box_head.conv3_ctr",
    "box_head.conv4_ctr",
    "box_head.conv5_ctr",
]
cfg.TRAIN.FREEZE_NONTRAINABLE_BN = True
cfg.TRAIN.SAVE_FINAL_ONLY = False
cfg.TRAIN.SAVE_LATEST_ONLY = False

cfg.TRAIN.CE_START_EPOCH = 20  # candidate elimination start epoch
cfg.TRAIN.CE_WARM_EPOCH = 80  # candidate elimination warm up epoch
cfg.TRAIN.DROP_PATH_RATE = 0.1  # drop path rate for ViT backbone

# TRAIN.SCHEDULER
cfg.TRAIN.SCHEDULER = edict()
cfg.TRAIN.SCHEDULER.TYPE = "step"
cfg.TRAIN.SCHEDULER.DECAY_RATE = 0.1

# DATA
cfg.DATA = edict()
cfg.DATA.SAMPLER_MODE = "causal"  # sampling methods
cfg.DATA.MEAN = [0.485, 0.456, 0.406]
cfg.DATA.STD = [0.229, 0.224, 0.225]
cfg.DATA.MAX_SAMPLE_INTERVAL = 200
# DATA.TRAIN
cfg.DATA.TRAIN = edict()
cfg.DATA.TRAIN.DATASETS_NAME = ["LASOT", "GOT10K_vottrain"]
cfg.DATA.TRAIN.DATASETS_RATIO = [1, 1]
cfg.DATA.TRAIN.SAMPLE_PER_EPOCH = 60000
# DATA.VAL
cfg.DATA.VAL = edict()
cfg.DATA.VAL.DATASETS_NAME = ["GOT10K_votval"]
cfg.DATA.VAL.DATASETS_RATIO = [1]
cfg.DATA.VAL.SAMPLE_PER_EPOCH = 10000
# DATA.SEARCH
cfg.DATA.SEARCH = edict()
cfg.DATA.SEARCH.SIZE = 320
cfg.DATA.SEARCH.FACTOR = 5.0
cfg.DATA.SEARCH.CENTER_JITTER = 4.5
cfg.DATA.SEARCH.SCALE_JITTER = 0.5
cfg.DATA.SEARCH.NUMBER = 1
# DATA.TEMPLATE
cfg.DATA.TEMPLATE = edict()
cfg.DATA.TEMPLATE.NUMBER = 1
cfg.DATA.TEMPLATE.SIZE = 128
cfg.DATA.TEMPLATE.FACTOR = 2.0
cfg.DATA.TEMPLATE.CENTER_JITTER = 0
cfg.DATA.TEMPLATE.SCALE_JITTER = 0

# TEST
cfg.TEST = edict()
cfg.TEST.TEMPLATE_FACTOR = 2.0
cfg.TEST.TEMPLATE_SIZE = 128
cfg.TEST.TEMPLATE_NUMBER = 1
cfg.TEST.MEMORY_THRESHOLD = 1000
cfg.TEST.SEARCH_FACTOR = 5.0
cfg.TEST.SEARCH_SIZE = 320
cfg.TEST.EPOCH = 500
cfg.TEST.LANGUAGE_INIT_SOURCE = "blip"  # blip, dataset_or_blip, dataset_or_class, class_or_blip
cfg.TEST.LANGUAGE_UPDATE_MODE = "caption_replace"  # caption_replace, anchor, off
cfg.TEST.LANGUAGE_TRIGGER_SCALE_THR = 0.95
cfg.TEST.LANGUAGE_TRIGGER_DISTANCE_STRIDE = 0.03125
cfg.TEST.LANGUAGE_TRIGGER_COLOR_ENABLE = False
cfg.TEST.LANGUAGE_TRIGGER_COLOR_THR = 35.0
cfg.TEST.LANGUAGE_WORD_FILTER_ENABLE = False
cfg.TEST.LANGUAGE_WORD_FILTER_THRESHOLD = 0.4
cfg.TEST.LANGUAGE_WORD_FILTER_MOMENTUM = 0.8
cfg.TEST.LANGUAGE_WORD_FILTER_MIN_KEEP = 2
cfg.TEST.LANGUAGE_WORD_RELIABILITY_ENABLE = False
cfg.TEST.LANGUAGE_WORD_RELIABILITY_SOURCE = "target_hardneg_gap"
cfg.TEST.LANGUAGE_WORD_RELIABILITY_MOMENTUM = 0.8
cfg.TEST.LANGUAGE_WORD_RELIABILITY_TAU = 0.1
cfg.TEST.LANGUAGE_SUBJECT_MIN_RELIABILITY = 0.7
cfg.TEST.LANGUAGE_CONTEXT_MAX_WEIGHT = 0.4
cfg.TEST.LANGUAGE_SUBJECT_TYPE_PRIOR = 1.0
cfg.TEST.LANGUAGE_ATTRIBUTE_TYPE_PRIOR = 1.0
cfg.TEST.LANGUAGE_CONTEXT_TYPE_PRIOR = 1.0
cfg.TEST.LANGUAGE_RELIABILITY_UPDATE_GATE = True
cfg.TEST.LANGUAGE_RELIABILITY_GATE_MODE = "score_gap"  # score_gap, score_peak, both
cfg.TEST.LANGUAGE_RELIABILITY_SCORE_THR = 0.4
cfg.TEST.LANGUAGE_RELIABILITY_SCORE_GAP_THR = 0.05


def _edict2dict(dest_dict, src_edict):
    if isinstance(dest_dict, dict) and isinstance(src_edict, dict):
        for k, v in src_edict.items():
            if not isinstance(v, edict):
                dest_dict[k] = v
            else:
                dest_dict[k] = {}
                _edict2dict(dest_dict[k], v)
    else:
        return


def gen_config(config_file):
    cfg_dict = {}
    _edict2dict(cfg_dict, cfg)
    with open(config_file, 'w') as f:
        yaml.dump(cfg_dict, f, default_flow_style=False)


def _update_config(base_cfg, exp_cfg):
    if isinstance(base_cfg, dict) and isinstance(exp_cfg, edict):
        for k, v in exp_cfg.items():
            if k in base_cfg:
                if not isinstance(v, dict):
                    base_cfg[k] = v
                else:
                    _update_config(base_cfg[k], v)
            else:
                raise ValueError("{} not exist in config.py".format(k))
    else:
        return


def update_config_from_file(filename, base_cfg=None):
    exp_config = None
    with open(filename) as f:
        exp_config = edict(yaml.safe_load(f))
        if base_cfg is not None:
            _update_config(base_cfg, exp_config)
        else:
            _update_config(cfg, exp_config)
